### PR TITLE
fix(check): Don't generalize variables from an outer scope ...

### LINKED ISSUE #77: Type signatures causes variables to be generalized to early
```f#
let make x =
    let y: m = x
    x

make
```
Gives a type of `m00 -> m01` whereas it should be `m00 -> m00`. This is caused by the type signature of `y` which unifies the type of `x` with the 'generic' variable `m` in the binding. Subsequent use of `x` instantiates `m` with a fresh variable which gives the resulting type where the variables are not equal.

### PR DESCRIPTION
**Pull request by Marwes**
... when merging with a type signature

This commit tracks all type variables introduced in type signatures and uses this information to emit an error when a variable from a signature is matched to a variable from an outer scope.

Fixes #77

### CODE REVIEW

**Comment by Marwes** [comment]
This still fails to compile the prelude as there are multiple places where a type signature is unified with a variable from a scope outside the type signature. Would like some feedback for how to fix this, see #77 for some ideas.

File: check/tests/fail.rs [hunk 1]
```diff
@@ -294,3 +294,17 @@ let g x: A a -> () = x
...
+    let text = r#"
+let make m =
+    let m2: m = m
+    m
+
+make
+"#;
+    let result = support::typecheck(text);
+    assert!(result.is_err());
+}
```
Comment (brendanzab) [inline check/tests/fail.rs]: Missing new line

File: check/tests/pass.rs [hunk 2]
```diff
@@ -827,3 +826,18 @@ in r1"#;
...
+let any x = any x
+let make m: m -> { test: m, test2: m } =
+    let m2: m = any ()
+    { test = m, test2 = m2 }
+
+make
+"#;
+    let result = support::typecheck(text);
+    assert!(result.is_ok(), "{}", result.unwrap_err());
+}
```
Comment (brendanzab) [inline check/tests/pass.rs]: Missing new line

**Comment by brendanzab** [comment]
```
Line: 69, Column: 9: Expected the following types to be equal
Expected: m -> m -> m
Found: 88 -> 88 -> 88
3 errors were found during unification:
Could not generalize the variable bound to `m` as the variable was used outside its scope
Could not generalize the variable bound to `m` as the variable was used outside its scope
Could not generalize the variable bound to `m` as the variable was used outside its scope
    let (<>) : m -> m -> m = append
        ^~
```

Well, now that I think about it, the current definition of `make_Monoid` is quite odd:

```
let make_Monoid m =
    let { append, empty } = m

    let (<>) : m -> m -> m = append

    { append, empty, (<>) }
```

What `make_Monoid` should *really* look like is this ('scuse the straw man syntax for implicits #98):

```
let make_Monoid [t] M: [t : Type] -> Monoid t -> { Monoid t | (<>) : t -> t -> t }  =
    let { append, empty } = M

    let (<>) : t -> t -> t = append

    { append, empty, (<>) }
```

Since we have no current way of bringing the `t` binding into scope, we shouldn't be able to explicitly type `(<>)`. I'm not sure if this is the source of the errors we are getting, but there is certainly something unsound in our current typechecker that wasn't getting found.

**Comment by Marwes** [comment]
Rebased. Fixed the nits and added some comments to the first commit, fixed a small mistake and commented out the failing type signatures in the other two commits

File: check/src/substitution.rs [hunk 3]
```diff
@@ -294,6 +294,10 @@ impl<T: Substitutable + PartialEq + Clone> Substitution<T> {
     pub fn union(&self, id: &T::Variable, typ: &T) -> Result<(), ()>
         where T::Variable: Clone
     {
+        // Nothing needs to be done if both are the same variable already (also prevents the occurs check from failing)
```
Comment (brendanzab) [inline check/src/substitution.rs]: > also prevents the occurs check from failing

What does this mean? Would `occurs` panic otherwise?

File: check/src/unify_type.rs [hunk 4]
```diff
@@ -375,6 +384,109 @@ fn walk_move_types2<'a, I, F, T>(mut types: I, replaced: bool, output: &mut Vec<
...
+    subs: &'e Substitution<TcType>,
+    variables: &'e ScopedMap<Symbol, TcType>,
+    errors: Errors<Error<Symbol>>,
+    level: u32,
+}
+
+impl<'a, 'e> Unifier<State<'a>, TcType> for Merge<'e> {
+    fn report_error(unifier: &mut UnifierState<Self>,
+                    error: UnifyError<TcType, TypeError<Symbol>>) {
+        unifier.unifier.errors.error(error);
```
Comment (brendanzab) [inline check/src/unify_type.rs]: The stutteriness is strong with this one... :3

File: check/src/substitution.rs (hunk 3 above)
Comment (Marwes) [inline check/src/substitution.rs]: No it would fail Typecheck ingredients with `123 occurs in 123` which is obviously nonsense. Unifying with itself should always succeed

File: check/src/unify_type.rs (hunk 4 above)
Comment (Marwes) [inline check/src/unify_type.rs]: And naming is hard :(

File: check/src/substitution.rs (hunk 3 above)
Comment (brendanzab) [inline check/src/substitution.rs]: Aha! Thanks!
